Added 2 HW's and their copies
LeviusBI/Python_BI_2022 pull request #3
Opened 2022-11-12 11:02 UTC by LeviusBI

2022-11-26 18:46 UTC, LeviusBI commented
Так, я что-то, видимо, накосячил, поэтому в данной ветке лежит ещё домашка с предыдущего дз. К проверке там только Visualisation.py, Panas.py, PandasVis.ipynb, Visualisation.ipynb. Я, вроде, переключался на main, когда создавал данную ветку, но, видимо, что-то сделал не так. Как минимум, в локальном репозитории других файлов нет, а гит показывал, что отслеживает только 4 перечисленных мною

2022-12-10 19:04 UTC, krglkvrmn requested changes
Хорошая работа
![image](https://user-images.githubusercontent.com/48160953/206871325-4a005262-1163-4779-ac6e-4ff0aefca256.png)

2022-12-10 19:04 UTC, krglkvrmn commented on Pandas.py
> +                                                                        'strand', 'phase', 'atributes'])
Твой код учитывает только случай, где комментарий занимает только первую строку. Однако чаще всего в файлах данного формата могут быть комментарии на много строк, их нужно учитывать. Благо в пандасе это делается супер просто
```suggestion
    df = pd.read_csv(gfffile, sep='\t', comment="#", names=['Chromosome', 'source',
                                                                        'type', 'start',
                                                                        'end', 'score',
                                                                        'strand', 'phase', 'atributes'])
```

2022-12-10 19:04 UTC, krglkvrmn commented on Pandas.py
> +table_gff['atributes']=table_gff['atributes'].replace(['Name=16S_rRNA;produc',
```suggestion
table_gff['atributes'] = table_gff['atributes'].replace(['Name=16S_rRNA;produc', 
```

2022-12-10 19:04 UTC, krglkvrmn commented on Pandas.py
> +rna_p_chr.unstack().plot.bar(figsize=(13,5), color={'16S':'pink', '23S':'yellow', '5S':'cyan'})
Классные цвета

2022-12-10 19:04 UTC, krglkvrmn commented on Pandas.py
> +                                                                        'strand', 'phase', 'atributes'])
Ещё я не совсем понял, что значит `comment="t"`, в чём виновата эта бедная буква(((

2022-12-10 19:04 UTC, krglkvrmn commented on Pandas.py
> +                                                                        'strand', 'phase', 'atributes'])
А, я понял, кажется, но тогда это костыль)

2022-12-10 19:04 UTC, krglkvrmn commented on Pandas.py
> +table_bed = read_bed6('alignment.bed')
Если код подразумевает работу с данными из каких-то файлов, то эти файлы обязательно нужно класть в репозиторий и указывать относительный путь до них. Исключение только одно - слишком большие файлы, в таком случае можно заливать их маленький кусочек.

2022-12-10 19:04 UTC, krglkvrmn commented on Pandas.py
> +suc_rna[(suc_rna['start_x'] >= suc_rna['start_y']) & (suc_rna['end_x'] <= suc_rna['end_y'])]
В итоговой табличке потерялась одна строка, скорее всего из-за косяков с чтением файлов

2022-12-10 19:04 UTC, krglkvrmn commented on Pandas.py
> +suc_rna[(suc_rna['start_x'] >= suc_rna['start_y']) & (suc_rna['end_x'] <= suc_rna['end_y'])]
Так-то решение верное

2022-12-10 19:04 UTC, krglkvrmn commented on Visualisation.py
> +df = pd.read_table('diffexpr_data.tsv.gz')
Не надо называть переменную df, если ты выкладываешь это код)
```suggestion
diffexpr_data = pd.read_table('diffexpr_data.tsv.gz')
```

2022-12-10 19:04 UTC, krglkvrmn commented on Visualisation.py
> +plt.savefig('volcplot.png', dpi = 300, bbox_inches = 'tight', edgecolor = 'b')
График из **Visualisation (copy).ipynb** мне нравится больше, поэтому оценивать буду его. Но вообще довольно странно иметь в репозитории файлы с суффиксом (copy)

Все пробелы куда-то убежали
```python
green=df[(df['logFC'] < 0) & (df['pval_corr'] >= 0.05)]
red=df[(df['logFC'] > 0) & (df['pval_corr'] >= 0.05)]
blue=df[(df['logFC'] < 0) & (df['pval_corr'] < 0.05)]
orange=df[(df['logFC'] > 0) & (df['pval_corr'] < 0.05)]
```

а тут наоборот лишние
```python
plt.scatter(x=green['logFC'], y=green['log_pval'], s = 2.5, c = 'green')
plt.scatter(x=red['logFC'], y=red['log_pval'], s = 2.5, c = 'red')
plt.scatter(x=blue['logFC'], y=blue['log_pval'], s = 2.5, c = 'blue')
plt.scatter(x=orange['logFC'], y=orange['log_pval'], s = 2.5, c = 'orange')
```

Первую координату можно приблизительно вычислить из данных
```python
plt.text(8, -np.log10(0.06), 'p value=0.05', weight='bold', fontsize=10, c='gray', alpha = 0.6)
```

Не хватает некоторых кастомизаций

1. Легенды (её вообще нет)
2. Курсива в подписях
3. Стрелок, аннотирующих топ-гены
4. Кастомизации ticks major

2022-12-13 01:18 UTC, LeviusBI commented on Pandas.py
> +table_bed = read_bed6('alignment.bed')
Понял, теперь буду класть

2022-12-13 01:18 UTC, LeviusBI commented on Visualisation.py
> +df = pd.read_table('diffexpr_data.tsv.gz')
А почему...

2022-12-13 01:20 UTC, LeviusBI commented on Visualisation.py
> +plt.savefig('volcplot.png', dpi = 300, bbox_inches = 'tight', edgecolor = 'b')
Вообще, я их специально создавал, потому что подумал, что нужна копия домашки (в плане не нормальный скрипт, а просто копия)●_●

2022-12-13 08:28 UTC, krglkvrmn commented on Visualisation.py
> +df = pd.read_table('diffexpr_data.tsv.gz')
Ну тип не понятно, что в ней лежит. Если уж очень сильно хочется показать, что это именно датафрейм, то можно хотя бы `<what's in the box>_df`

2022-12-17 16:39 UTC, LeviusBI commented on Pandas.py
> +rna_p_chr.unstack().plot.bar(figsize=(13,5), color={'16S':'pink', '23S':'yellow', '5S':'cyan'})
Я сидел и выбирал их вместо того, чтобы учиться писать нормальный код.

2022-12-17 16:40 UTC, merged